### ISSUE TITLE
What about adding also codenames to OS X versions (e.g. "Snow Leopard")?

### ISSUE THREAD

**Issue by telatin** [tsibley/apple-perl-versions#1]
While the most relevant information is already present in this useful repository (OS X numeric version and Perl version), I think it would be a very nice touch to add a column with the codename...

**Comment by tsibley** [comment]
I'm glad you find the version information useful!  I agree the macOS / OS X marketing names would be good to have, but I'm not sure where to find such a data file.  Do you know of one?

**Comment by tsibley** [comment]
On second thought, I can probably just include a static list and join that in.  Updates don't happen super frequently.
